apiVersion: apps/v1
kind: Deployment
metadata:
  name: os-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: os-service
  template:
    metadata:
      labels:
        app: os-service
    spec:
      automountServiceAccountToken: false
      containers:
      - name: os-service
        image: fiap-oficina-os-service:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        env:
        - name: ConnectionStrings__postgres
          value: "${DB_CONNECTION_STRING}"
        - name: ConnectionStrings__messaging
          value: "${MESSAGING_CONNECTION}"
        - name: Authentication__Enabled
          value: "true"
        - name: JWT_KEY
          value: "${JWT_KEY}"
        - name: JWT_ISSUER
          value: "${JWT_ISSUER}"
        - name: JWT_AUDIENCE
          value: "${JWT_AUDIENCE}"
