using Microsoft.EntityFrameworkCore;
using FiapOficina.OSService.Api.Models;

namespace FiapOficina.OSService.Api.Infrastructure;

[System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public static class DatabaseInitializer
{
    public static void InitializeDatabase(OSDbContext dbContext)
    {
        dbContext.Database.EnsureCreated();

        // Garante que todo o esquema de tabelas e índices exista caso o banco já existisse na AWS
        dbContext.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""InboxState"" (
                ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
                ""MessageId"" uuid NOT NULL,
                ""ConsumerId"" uuid NOT NULL,
                ""LockId"" uuid NOT NULL,
                ""RowVersion"" bytea,
                ""Received"" timestamp with time zone NOT NULL,
                ""ReceiveCount"" integer NOT NULL,
                ""ExpirationTime"" timestamp with time zone,
                ""Consumed"" timestamp with time zone,
                ""Delivered"" timestamp with time zone,
                ""LastSequenceNumber"" bigint,
                CONSTRAINT ""PK_InboxState"" PRIMARY KEY (""Id""),
                CONSTRAINT ""AK_InboxState_MessageId_ConsumerId"" UNIQUE (""MessageId"", ""ConsumerId"")
            );

            CREATE TABLE IF NOT EXISTS ""OrderStates"" (
                ""CorrelationId"" uuid NOT NULL,
                ""CurrentState"" text NOT NULL,
                ""CreatedAt"" timestamp with time zone NOT NULL,
                ""BudgetedAt"" timestamp with time zone,
                ""ApprovedAt"" timestamp with time zone,
                ""PaidAt"" timestamp with time zone,
                ""FinishedAt"" timestamp with time zone,
                ""BudgetId"" uuid,
                ""Amount"" numeric NOT NULL,
                CONSTRAINT ""PK_OrderStates"" PRIMARY KEY (""CorrelationId"")
            );

            CREATE TABLE IF NOT EXISTS ""OutboxMessage"" (
                ""SequenceNumber"" bigint GENERATED BY DEFAULT AS IDENTITY,
                ""EnqueueTime"" timestamp with time zone,
                ""SentTime"" timestamp with time zone NOT NULL,
                ""Headers"" text,
                ""Properties"" text,
                ""InboxMessageId"" uuid,
                ""InboxConsumerId"" uuid,
                ""OutboxId"" uuid,
                ""MessageId"" uuid NOT NULL,
                ""ContentType"" character varying(256) NOT NULL,
                ""MessageType"" text NOT NULL,
                ""Body"" text NOT NULL,
                ""ConversationId"" uuid,
                ""CorrelationId"" uuid,
                ""InitiatorId"" uuid,
                ""RequestId"" uuid,
                ""SourceAddress"" character varying(256),
                ""DestinationAddress"" character varying(256),
                ""ResponseAddress"" character varying(256),
                ""FaultAddress"" character varying(256),
                ""ExpirationTime"" timestamp with time zone,
                CONSTRAINT ""PK_OutboxMessage"" PRIMARY KEY (""SequenceNumber"")
            );

            CREATE TABLE IF NOT EXISTS ""OutboxState"" (
                ""OutboxId"" uuid NOT NULL,
                ""LockId"" uuid NOT NULL,
                ""RowVersion"" bytea,
                ""Created"" timestamp with time zone NOT NULL,
                ""Delivered"" timestamp with time zone,
                ""LastSequenceNumber"" bigint,
                CONSTRAINT ""PK_OutboxState"" PRIMARY KEY (""OutboxId"")
            );

            CREATE TABLE IF NOT EXISTS ""ServiceOrders"" (
                ""Id"" uuid NOT NULL,
                ""VehicleId"" uuid NOT NULL,
                ""CustomerName"" text NOT NULL,
                ""VehiclePlate"" text NOT NULL,
                ""EstimatedValue"" numeric NOT NULL,
                ""Status"" integer NOT NULL,
                ""CreatedOn"" timestamp with time zone NOT NULL,
                ""ApprovedOn"" timestamp with time zone,
                ""FinishedOn"" timestamp with time zone,
                CONSTRAINT ""PK_ServiceOrders"" PRIMARY KEY (""Id"")
            );

            CREATE TABLE IF NOT EXISTS ""Users"" (
                ""Id"" uuid NOT NULL,
                ""Username"" text NOT NULL,
                ""Name"" text NOT NULL,
                ""Role"" text NOT NULL,
                ""Password"" text NOT NULL,
                CONSTRAINT ""PK_Users"" PRIMARY KEY (""Id"")
            );

            CREATE INDEX IF NOT EXISTS ""IX_InboxState_Delivered"" ON ""InboxState"" (""Delivered"");
            CREATE INDEX IF NOT EXISTS ""IX_OutboxMessage_EnqueueTime"" ON ""OutboxMessage"" (""EnqueueTime"");
            CREATE INDEX IF NOT EXISTS ""IX_OutboxMessage_ExpirationTime"" ON ""OutboxMessage"" (""ExpirationTime"");
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber"" ON ""OutboxMessage"" (""InboxMessageId"", ""InboxConsumerId"", ""SequenceNumber"");
            CREATE UNIQUE INDEX IF NOT EXISTS ""IX_OutboxMessage_OutboxId_SequenceNumber"" ON ""OutboxMessage"" (""OutboxId"", ""SequenceNumber"");
            CREATE INDEX IF NOT EXISTS ""IX_OutboxState_Created"" ON ""OutboxState"" (""Created"");
        ");

        if (!dbContext.Users.Any())
        {
            dbContext.Users.Add(new User
            {
                Id = Guid.NewGuid(),
                Username = "admin",
                Name = "System Operator",
                Role = "Operator",
                Password = "admin" // NOSONAR
            });
            dbContext.SaveChanges();
        }
    }
}
